### ISSUE TITLE
Style/HashSyntax EnforcedShorthandSyntax setting

### ISSUE THREAD

**Issue by ojgarcia** [Shopify/ruby-style-guide#393]
Rubocop will always enforce ruby's 3.1 hash key shorthand syntax by default. Do we want to change the default behavior?

The [Hash Literal Values](https://github.com/rubocop/ruby-style-guide#hash-literal-values) says this is good. 
For what its worth, [Standard](https://github.com/testdouble/standard/issues/375) is set to either.

Weak opinion: My preference would be to set it to either. Allow its use but not require it.

![Screen Shot 2022-05-20 at 2 27 28 PM](https://user-images.githubusercontent.com/3163908/169590364-5dcfae25-3faf-404c-959b-4abceab34f49.png)

**Comment by sambostock** [comment]
We have already set it to `either` 👍https://github.com/Shopify/ruby-style-guide/blob/5f9071c47cd125c3833d3fb5e8473c2020dfd6f0/rubocop.yml#L487-L488
