### ISSUE TITLE
Cut a release to eliminate rubocop 1.4 warning?

### ISSUE THREAD

**Issue by exterm** [Shopify/ruby-style-guide#491]
Hi friends!

Just updated rubocop, and I now get a warning because `Style/ArrayIntersect` is not configured. I could configure it on my side but would rather just have a release of ruby-style-guide that does it for me (as done by @sambostock in https://github.com/Shopify/ruby-style-guide/pull/487). 

If you could cut a new release, that would be most appreciated!

**Comment by sambostock** [comment]
@exterm 2.12 has been released. On a related note, #479 disallowed pending cops, so as long as we stay up to date on releases of Rubocop, pending cop warnings should reduced.
