### ISSUE TITLE
Consider re-evaluating Style/ModuleFunction: extend_self

### ISSUE THREAD

**Issue by jasonkarns** [Shopify/ruby-style-guide#616]
Has the decision to enforce `extend_self` over `module_function` ever been revisited internally?

The whole point of `module_function` is to allow namespaced stateless methods to be available as public class methods, while simultaneously included as private helper methods (when those methods are oft-used in a particular class) without polluting the class' public api. `extend self` isn't compatible with `module_function` because the visibility of the methods is forced to be the same at both the class and instance level.

When `extend self; private` is used to avoid polluting the  class' instance api, then you can't invoke them statically. But if you make them public so they can be namespaced utility methods, then they pollute the class' public api! 

This implies these two approaches aren't solving the same problem. `module_function` is purpose built to have different visibility. `extend self` is an idiom that is used for a variety of _other_ purposes that only _appears_ to overlap with `module_function`. But it has a bigger ramification than was likely recognized when it become oft-used/cargo-culted.

I dug into the history of the cop's setting. It seems the [initial decision](https://github.com/Shopify/ruby-style-guide/pull/28) was at least partially (if not primarily?) about `class << self` vs `def self.`. Nothing in the issue thread speaks to the nuance that `module_function` provides; wherein methods are desired to have different visibilities because they serve different purposes (public as class; private as instance). Since the initial discussion didn't seem to take these different purposes and behaviors into account, I'm hoping to at least broach that topic here.

**Comment by rafaelfranca** [comment]
Yeah, we considered it and decided we don't get much value on forcing people to use `module_function`. It is very rare in our codebases that the nuances you bring about `module_function` is actually what we need. We have very few instances of modules that are included in classes and also have static class methods.
