### ISSUE TITLE
Style guide style improvements

### ISSUE THREAD

**Issue by sambostock** [Shopify/ruby-style-guide#74]
Not a huge deal, but I thought I'd throw this out there.

I really like the way AirBnB does their [Javascript Style Guide](https://github.com/airbnb/javascript), for the following reasons:

- Table of Contents 📄
- Linking to specific sections 👈
- Examples for almost everything, often with 😇 good vs 👿 bad
- "Why"s on many style rules 🤔 

In my opinion, these make the style guide much more approachable to developers new to a language, as well as making the rules easier to share with others/refer to. I like having a "why" too, because rules make so much more sense when they aren't arbitrary.

**Comment by volmer** [comment]
Closing this in favour of more specific issues for each of the items described above. See #187 #188 #189 #190
